"""create companies table

Canonical Company schema (STORY-011) — see app/models/company.py for full
field-by-field rationale. Adds companies (name/normalized_name/domain/
company_metadata) and a nullable jobs.company_id FK (ON DELETE SET NULL —
deleting a company must never cascade-delete job listings). jobs.company_name
is untouched. One basic index on jobs.company_id (FK-lookup hygiene; Postgres
does not auto-index FK columns) — deliberately not STORY-057's broader
indexing strategy.

Autogenerated, then hand-edited to (1) give the FK constraint an explicit
name — autogenerate left it unnamed, which would have made
`op.drop_constraint(None, ...)` fail in downgrade() — and (2) add the FK
index, which autogenerate does not detect since it isn't declared on the
model.

Revision ID: 12606c63412f
Revises: 2e0df3bbe4b0
Create Date: 2026-08-20 01:48:33.719949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12606c63412f'
down_revision: Union[str, None] = '2e0df3bbe4b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('company_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', name='uq_companies_normalized_name')
    )
    op.add_column('jobs', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_jobs_company_id_companies',
        'jobs', 'companies', ['company_id'], ['id'], ondelete='SET NULL',
    )
    op.create_index('ix_jobs_company_id', 'jobs', ['company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_company_id', table_name='jobs')
    op.drop_constraint('fk_jobs_company_id_companies', 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'company_id')
    op.drop_table('companies')
    # ### end Alembic commands ###
