"""create jobs table

Canonical Job Listing schema (STORY-010) — see app/models/job.py for full
field-by-field rationale (nullability, enum choices, why company_id is
deliberately absent). Autogenerated from that model and reviewed unmodified;
downgrade cleanly drops the table since nothing references it yet.

Revision ID: 2e0df3bbe4b0
Revises: 02b03a7430e2
Create Date: 2026-08-20 01:24:36.628687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e0df3bbe4b0'
down_revision: Union[str, None] = '02b03a7430e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('source_job_id', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=500), nullable=True),
    sa.Column('description_full', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('preferred_requirements', sa.Text(), nullable=True),
    sa.Column('qualifications', sa.Text(), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('skills_raw', sa.Text(), nullable=True),
    sa.Column('location_raw', sa.String(length=500), nullable=True),
    sa.Column('location_city', sa.String(length=255), nullable=True),
    sa.Column('location_region', sa.String(length=255), nullable=True),
    sa.Column('location_country', sa.String(length=255), nullable=True),
    sa.Column('work_mode', sa.String(length=20), nullable=True),
    sa.Column('employment_type', sa.String(length=20), nullable=True),
    sa.Column('seniority', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('compensation_min', sa.Numeric(), nullable=True),
    sa.Column('compensation_max', sa.Numeric(), nullable=True),
    sa.Column('compensation_currency', sa.String(length=3), nullable=True),
    sa.Column('compensation_period', sa.String(length=20), nullable=True),
    sa.Column('benefits', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('posting_date', sa.Date(), nullable=True),
    sa.Column('closing_date', sa.Date(), nullable=True),
    sa.Column('application_url', sa.String(length=2048), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("employment_type IS NULL OR employment_type IN ('full_time', 'part_time', 'contract', 'temporary', 'internship', 'apprenticeship', 'other')", name='ck_jobs_employment_type'),
    sa.CheckConstraint("work_mode IS NULL OR work_mode IN ('remote', 'hybrid', 'on_site')", name='ck_jobs_work_mode'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_job_id', name='uq_jobs_source_source_job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
