"""add job indexes

Database Indexing Strategy (STORY-057) — see app/models/job.py's
__table_args__ for full per-index rationale (partial indexes on
work_mode/employment_type excluding NULL since Greenhouse never populates
either; composite location index broadest-to-narrowest; posting_date for
STORY-032's "newest first" sort; GIN expression index over exactly
STORY-030's literal title/company/description/skills full-text field list
-- this Story builds the index only, STORY-030 owns the search query/API).
jobs_search_vector_english(title, company, description, skills) is a
hand-written IMMUTABLE SQL wrapper around the full coalesce/concatenation/
to_tsvector('english', ...) expression. Discovered during implementation,
via two separate failed CREATE INDEX attempts against the real database:
Postgres marks both to_tsvector() overloads AND array_to_string() only
STABLE, not IMMUTABLE, and CREATE INDEX categorically rejects any
non-IMMUTABLE function anywhere in an index expression. Wrapping the whole
expression inside one custom SQL function explicitly labeled IMMUTABLE is
the standard, documented Postgres workaround: Postgres trusts a function's
declared volatility rather than inspecting what it calls internally. Safe
here because the language config ('english') is a hardcoded literal, never
a column value. Hand-written (not autogenerated) for the function itself --
Alembic's autogenerate has no concept of creating a SQL function -- while
the index/DROP INDEX statements themselves came from --autogenerate and
were reviewed, then adjusted only to call the new wrapper instead of
to_tsvector()/array_to_string() directly.

Revision ID: 4a2ec55ea99c
Revises: 957d3cc4bfc0
Create Date: 2026-08-21 23:05:19.324746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a2ec55ea99c'
down_revision: Union[str, None] = '957d3cc4bfc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE FUNCTION jobs_search_vector_english(
            title text, company text, description text, skills text[]
        )
        RETURNS tsvector
        LANGUAGE sql
        IMMUTABLE
        PARALLEL SAFE
        AS $$
            SELECT to_tsvector('english',
                coalesce(title, '') || ' ' ||
                coalesce(company, '') || ' ' ||
                coalesce(description, '') || ' ' ||
                coalesce(array_to_string(skills, ' '), '')
            )
        $$
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_jobs_employment_type', 'jobs', ['employment_type'], unique=False, postgresql_where=sa.text('employment_type IS NOT NULL'))
    op.create_index('ix_jobs_location_country_region_city', 'jobs', ['location_country', 'location_region', 'location_city'], unique=False)
    op.create_index('ix_jobs_posting_date', 'jobs', ['posting_date'], unique=False)
    op.create_index('ix_jobs_search_vector', 'jobs', [sa.text("jobs_search_vector_english(job_title, company_name, description_full, skills)")], unique=False, postgresql_using='gin')
    op.create_index('ix_jobs_work_mode', 'jobs', ['work_mode'], unique=False, postgresql_where=sa.text('work_mode IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_work_mode', table_name='jobs', postgresql_where=sa.text('work_mode IS NOT NULL'))
    op.drop_index('ix_jobs_search_vector', table_name='jobs', postgresql_using='gin')
    op.drop_index('ix_jobs_posting_date', table_name='jobs')
    op.drop_index('ix_jobs_location_country_region_city', table_name='jobs')
    op.drop_index('ix_jobs_employment_type', table_name='jobs', postgresql_where=sa.text('employment_type IS NOT NULL'))
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION jobs_search_vector_english(text, text, text, text[])")
