"""create ingestion_runs table

Ingestion Run Tracking (STORY-015) — see app/models/ingestion_run.py for
full field-by-field rationale (why jobs_seen/created/updated/failed match
requirement.md literally instead of the differently-named counters a prompt
template suggested, why source_id is nullable with ON DELETE SET NULL, why
there's no service layer). Autogenerated and applied unmodified — no
unnamed-constraint or missing-index issues, since the model already
declares an explicit FK name and `index=True` (lessons from STORY-011,
applied proactively since STORY-014).

Revision ID: 957d3cc4bfc0
Revises: cbe997a1b1db
Create Date: 2026-08-20 02:37:45.306473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957d3cc4bfc0'
down_revision: Union[str, None] = 'cbe997a1b1db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'running'"), nullable=False),
    sa.Column('jobs_seen', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('jobs_created', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('jobs_updated', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('jobs_failed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('running', 'success', 'failed')", name='ck_ingestion_runs_status'),
    sa.CheckConstraint('jobs_created >= 0', name='ck_ingestion_runs_jobs_created_non_negative'),
    sa.CheckConstraint('jobs_failed >= 0', name='ck_ingestion_runs_jobs_failed_non_negative'),
    sa.CheckConstraint('jobs_seen >= 0', name='ck_ingestion_runs_jobs_seen_non_negative'),
    sa.CheckConstraint('jobs_updated >= 0', name='ck_ingestion_runs_jobs_updated_non_negative'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name='fk_ingestion_runs_source_id_sources', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_source_id'), 'ingestion_runs', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_runs_source_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
