"""create sources table

Source Registry (STORY-014) — see app/models/source.py for full field-by-
field rationale (why company_id is a proposed extension beyond the literal
Story text, why connector_type has no closed set, why last_run_summary is
one JSONB field). Autogenerated and applied unmodified — no unnamed-
constraint or missing-index issues this time, since the model already
declares an explicit FK name and `index=True` (lessons from STORY-011).

Revision ID: cbe997a1b1db
Revises: 12606c63412f
Create Date: 2026-08-20 02:15:47.799621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbe997a1b1db'
down_revision: Union[str, None] = '12606c63412f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_run_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("connector_type <> ''", name='ck_sources_connector_type_not_empty'),
    sa.CheckConstraint("name <> ''", name='ck_sources_name_not_empty'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_sources_company_id_companies', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_company_id'), 'sources', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_company_id'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
