"""HTML sanitization for externally-sourced job content (STORY-047).

Every connector-provided free-text "section" field (`description_full`,
`responsibilities`, `requirements`, `preferred_requirements`,
`qualifications`) is untrusted external HTML -- a source's own markup,
never generated by this application. `sanitize_html()` is called once,
centrally, in the shared ingestion pipeline
(`app.ingestion.orchestrator.run_source()`) before persistence -- not
per-connector, per STORY-016's own "shared pipeline, not per connector"
principle. It is the same function STORY-034 (Job Detail Page, not yet
built) will call again at render time, satisfying this Story's own
"sanitize on ingest, treat the stored value as still-untrusted at render
time" requirement without retrofitting a page that doesn't exist yet.

`skills`/`benefits` are deliberately out of scope: short, keyword-like
list-of-string fields, not treated as HTML-bearing content by any current
connector.

Uses `nh3` (Mozilla's Rust-backed `ammonia` binding) rather than a
hand-rolled regex-based sanitizer -- getting this right by hand (safe
attribute handling, URL-scheme filtering, malformed-markup resilience) is
exactly the kind of security-critical, easy-to-get-wrong task this
project has previously drawn the line at needing a real library for (see
`prometheus_client`, STORY-051).

Allow-list is explicit rather than relying on the library's own defaults,
for a documented, deterministic policy: common job-description formatting
only (paragraphs, line breaks, lists, basic emphasis, headings, links).
`nh3`'s default `link_rel` behavior (unchanged here) forces
`rel="noopener noreferrer"` onto every surviving `<a>` -- verified live:
`javascript:`-scheme hrefs are dropped entirely (not merely neutralized to
`#`), since `nh3` only allows http/https/mailto schemes by default.
"""

from __future__ import annotations

import nh3

_ALLOWED_TAGS = {
    "p",
    "br",
    "ul",
    "ol",
    "li",
    "strong",
    "b",
    "em",
    "i",
    "u",
    "a",
    "h1",
    "h2",
    "h3",
    "h4",
    "span",
}

_ALLOWED_ATTRIBUTES = {"a": {"href"}}


def sanitize_html(value: str | None) -> str | None:
    """Strips disallowed tags/attributes (scripts, styles, event handlers,
    unsafe URL schemes) from externally-sourced HTML, preserving basic
    formatting. `None` in, `None` out -- absence is never fabricated into
    an empty string."""
    if value is None:
        return None
    return nh3.clean(value, tags=_ALLOWED_TAGS, attributes=_ALLOWED_ATTRIBUTES)
